
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Namat
 */
public class Sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Sing_up
     */
    public Sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastN_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Father_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Student_num_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        city_comboBox = new javax.swing.JComboBox<String>();
        country_combobox = new javax.swing.JComboBox<String>();
        Department_comboBox = new javax.swing.JComboBox<String>();
        faculty_comboBox = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Male_radioButton = new javax.swing.JRadioButton();
        Female_radioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        Bith_date_field = new javax.swing.JTextField();
        Update_button = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();
        Insert_button2 = new javax.swing.JButton();
        year_field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        message_text = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(200, 50, 0, 0));

        jLabel1.setText("Name");

        Name_field.setToolTipText("");

        jLabel2.setText("Last Name");

        jLabel3.setText("Fathar Name");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("Student number");

        jLabel6.setText("phone number");

        jLabel7.setText("Email Address");

        city_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bishkek", "Narin", "Isyk kul", "Talas", "Osh", "Batkin", "Other" }));

        country_combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Kyrgyzstan", "Turkey", "Russia", "Afghanistan", "Tajikistan", "Ozbekistan", "Turkmenistan", "Kazakistan", "Other" }));

        Department_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Department of Horticulture and Agronomy", "Department of Plant Protection", "Department of Animal Science", "Department of Public Relations and Advertising", "Department of Radio, Television and Cinema", "Department of Economy", "Department of Management", "Department of Finance", "Department of International Relations", "Department of Finance and Banking", "Department of Computer Engineering", "Department of Chemical Engineering", "Department of Food Engineering", "Department of Ecological Engineering", "Department of Industry Engineering", "Department of Electrical Engineering", "Department of Painting", "Department of Performing Arts", "Department of Western Languages", "Department of Eastern Languages", "Department of Educational Science", "Department of Philosophy", "Department of Sociology", "Department of History", "Department of Turkology", "Department of Translations", "Department of Mathematics", "Department of Applied Mathematics and Informatics", "Department of Biology", "Department of Islamic Studies", "Department of Religious Studies", "Other" }));
        Department_comboBox.setMinimumSize(new java.awt.Dimension(274, 200));
        Department_comboBox.setPreferredSize(new java.awt.Dimension(274, 400));
        Department_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Department_comboBoxActionPerformed(evt);
            }
        });

        faculty_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Latter", "Economics and Administrative Sciences", "Communication", "Engineering", "Language", "Medicine", "SCHOOL OF TOURISM AND HOTELING", "Agriculture", "Veterinary", "Fine Arts", "HIGH SCHOOL OF PHYSICAL EDUCATION AND SPORTS", "Sciences", "Fine Arts Resim", "Theology", " ", " " }));
        faculty_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculty_comboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Select your country");

        jLabel9.setText("Select your city");

        jLabel10.setText("Select your faculty");

        jLabel11.setText("Select your department");

        jLabel12.setText("Gender");

        buttonGroup1.add(Male_radioButton);
        Male_radioButton.setText("Male");

        buttonGroup1.add(Female_radioButton);
        Female_radioButton.setText("Female");

        jLabel14.setText("Birth Day   (dat/month/year)");

        Update_button.setText("Update");

        Back_button.setText("Back");

        Insert_button2.setText("Insert");

        jLabel13.setText("Year");

        message_text.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Name_field)
                                            .addComponent(year_field, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(Student_num_field)
                                            .addComponent(LastN_field)
                                            .addComponent(Father_field)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(city_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faculty_comboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Department_comboBox, 0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Bith_date_field, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Male_radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Female_radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Insert_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(message_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(559, Short.MAX_VALUE)
                    .addComponent(country_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastN_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Father_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_num_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(city_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(faculty_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Department_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Male_radioButton)
                    .addComponent(Female_radioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bith_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_field)
                    .addComponent(message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Insert_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(country_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Department_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Department_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Department_comboBoxActionPerformed

    private void faculty_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculty_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faculty_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Sign_up().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JTextField Bith_date_field;
    private javax.swing.JComboBox<String> Department_comboBox;
    private javax.swing.JTextField Father_field;
    private javax.swing.JRadioButton Female_radioButton;
    private javax.swing.JButton Insert_button2;
    private javax.swing.JTextField LastN_field;
    private javax.swing.JRadioButton Male_radioButton;
    private javax.swing.JTextField Name_field;
    private javax.swing.JTextField Student_num_field;
    private javax.swing.JButton Update_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> city_comboBox;
    private javax.swing.JComboBox<String> country_combobox;
    private javax.swing.JTextField email_field;
    private javax.swing.JComboBox<String> faculty_comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel message_text;
    private javax.swing.JTextField phone_field;
    private javax.swing.JTextField year_field;
    // End of variables declaration//GEN-END:variables

    public JButton getBack_button() {
        return Back_button;
    }

    public void setBack_button(JButton Back_button) {
        this.Back_button = Back_button;
    }

    public JTextField getBith_date_field() {
        return Bith_date_field;
    }

    public void setBith_date_field(JTextField Bith_date_field) {
        this.Bith_date_field = Bith_date_field;
    }

    public JButton getUpdate_button() {
        return Update_button;
    }

    public void setUpdate_button(JButton Update_button) {
        this.Update_button = Update_button;
    }

    

    public JComboBox<String> getDepartment_comboBox() {
        return Department_comboBox;
    }

    public void setDepartment_comboBox(JComboBox<String> Department_comboBox) {
        this.Department_comboBox = Department_comboBox;
    }

  

    public JTextField getFather_field() {
        return Father_field;
    }

    public void setFather_field(JTextField Father_field) {
        this.Father_field = Father_field;
    }

    public JRadioButton getFemale_radioButton() {
        return Female_radioButton;
    }

    public void setFemale_radioButton(JRadioButton Female_radioButton) {
        this.Female_radioButton = Female_radioButton;
    }

    public JButton getInsert_button2() {
        return Insert_button2;
    }

    public void setInsert_button2(JButton Insert_button2) {
        this.Insert_button2 = Insert_button2;
    }

    public JTextField getLastN_field() {
        return LastN_field;
    }

    public void setLastN_field(JTextField LastN_field) {
        this.LastN_field = LastN_field;
    }

    public JRadioButton getMale_radioButton() {
        return Male_radioButton;
    }

    public void setMale_radioButton(JRadioButton Male_radioButton) {
        this.Male_radioButton = Male_radioButton;
    }

    public JTextField getName_field() {
        return Name_field;
    }

    public void setName_field(JTextField Name_field) {
        this.Name_field = Name_field;
    }

    public JTextField getStudent_num_field() {
        return Student_num_field;
    }

    public void setStudent_num_field(JTextField Student_num_field) {
        this.Student_num_field = Student_num_field;
    }

    public JComboBox<String> getCity_comboBox() {
        return city_comboBox;
    }

    public void setCity_comboBox(JComboBox<String> city_comboBox) {
        this.city_comboBox = city_comboBox;
    }

    public JComboBox<String> getCountry_combobox() {
        return country_combobox;
    }

    public void setCountry_combobox(JComboBox<String> country_combobox) {
        this.country_combobox = country_combobox;
    }

    public JTextField getEmail_field() {
        return email_field;
    }

    public void setEmail_field(JTextField email_field) {
        this.email_field = email_field;
    }

    public JComboBox<String> getFaculty_comboBox() {
        return faculty_comboBox;
    }

    public void setFaculty_comboBox(JComboBox<String> faculty_comboBox) {
        this.faculty_comboBox = faculty_comboBox;
    }

    public JTextField getPhone_field() {
        return phone_field;
    }

    public void setPhone_field(JTextField phone_field) {
        this.phone_field = phone_field;
    }

    public JTextField getYear_field() {
        return year_field;
    }

    public void setYear_field(JTextField year_field) {
        this.year_field = year_field;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JLabel getMessage_text() {
        return message_text;
    }

    public void setMessage_text(JLabel message_text) {
        this.message_text = message_text;
    }

}
