
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Namat
 */
public class View extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    Model model=new Model();
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        tableModel=(DefaultTableModel)table_list.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_list = new javax.swing.JTable();
        searching_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        update_button = new javax.swing.JButton();
        Insert_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        message_text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFile_item = new javax.swing.JMenuItem();
        savetofile_item = new javax.swing.JMenuItem();
        close_item = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 10, 0, 0));

        table_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last Name", "Job"
            }
        ));
        table_list.setColumnSelectionAllowed(true);
        table_list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(table_list);

        searching_field.setToolTipText("searching");
        searching_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searching_fieldFocusLost(evt);
            }
        });
        searching_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_fieldMouseClicked(evt);
            }
        });
        searching_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_fieldActionPerformed(evt);
            }
        });
        searching_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searching_fieldKeyReleased(evt);
            }
        });

        update_button.setText("Update");

        Insert_Button.setText("Insert");

        Delete_Button.setText("Delete");

        message_text.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("searching");

        jMenu1.setText("File      ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        openFile_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFile_item.setText("open file");
        jMenu1.add(openFile_item);

        savetofile_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        savetofile_item.setText("save to file");
        jMenu1.add(savetofile_item);

        close_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        close_item.setText("close");
        close_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_itemActionPerformed(evt);
            }
        });
        jMenu1.add(close_item);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit      ");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(753, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searching_field, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 187, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searching_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searching_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_fieldActionPerformed

    private void searching_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searching_fieldFocusLost
       
       
    }//GEN-LAST:event_searching_fieldFocusLost

    private void searching_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_fieldMouseClicked
//        if(searching_field.getText().equals("Searching")){
//            searching_field.setText("");
//        }
        
    }//GEN-LAST:event_searching_fieldMouseClicked
    public void Daynamic_search(String search){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(tableModel);
        
        table_list.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(search));
    }
    
    private void searching_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searching_fieldKeyReleased
        String search=searching_field.getText();
        
        Daynamic_search(search);
    }//GEN-LAST:event_searching_fieldKeyReleased

    private void close_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_close_itemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Insert_Button;
    private javax.swing.JMenuItem close_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel message_text;
    private javax.swing.JMenuItem openFile_item;
    private javax.swing.JMenuItem savetofile_item;
    private javax.swing.JTextField searching_field;
    private javax.swing.JTable table_list;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

    public JButton getDelete_Button() {
        return Delete_Button;
    }

    public void setDelete_Button(JButton Delete_Button) {
        this.Delete_Button = Delete_Button;
    }

    public JButton getInsert_Button() {
        return Insert_Button;
    }

    public void setInsert_Button(JButton Insert_Button) {
        this.Insert_Button = Insert_Button;
    }

    public JButton getSearch_button() {
        return update_button;
    }

    public void setSearch_button(JButton Search_button) {
        this.update_button = Search_button;
    }

    public JLabel getMessage_text() {
        return message_text;
    }

    public void setMessage_text(JLabel message_text) {
        this.message_text = message_text;
    }

    public JButton getUpdate_button() {
        return update_button;
    }

    public void setUpdate_button(JButton update_button) {
        this.update_button = update_button;
    }

    public JTable getTable_list() {
        return table_list;
    }

    public JTextField getSearching_field() {
        return searching_field;
    }

    public void setSearching_field(JTextField searching_field) {
        this.searching_field = searching_field;
    }

    public void setTable_list(JTable table_list) {
        this.table_list = table_list;
    }

    public JMenuItem getClose_item() {
        return close_item;
    }

    public void setClose_item(JMenuItem close_item) {
        this.close_item = close_item;
    }

    public JMenuItem getOpenFile_item() {
        return openFile_item;
    }

    public void setOpenFile_item(JMenuItem openFile_item) {
        this.openFile_item = openFile_item;
    }

    public JMenuItem getSavetofile_item() {
        return savetofile_item;
    }

    public void setSavetofile_item(JMenuItem savetofile_item) {
        this.savetofile_item = savetofile_item;
    }

   


}
